### ISSUE TITLE
[ENGINE] Unit testing

### ISSUE THREAD

**Issue by TheBlackParade** [runejs/server#13]
Implement basic unit test handling via either Jasmine or Jest. Tests do not need to be comprehensive at this time.

**Comment by Jameskmonger** [comment]
Please see this PR https://github.com/runejs/server/pull/366

**Comment by Jameskmonger** [comment]
@Kikorono I think that this can now be closed 😄

**Comment by SchauweM** [comment]
Going to close this indeed @Jameskmonger. We should add a new issue which is better described as to what has to happen regarding missing tests etc.
